

✅ Using parameters of pd.DataFrame()
pd.DataFrame(
    data=None,
    index=None,
    columns=None,
    dtype=None,
    copy=False
)

Example:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data, index=['x', 'y', 'z'], dtype=float, copy=True)
print(df)


Output:

     A    B
x  1.0  4.0
y  2.0  5.0
z  3.0  6.0

✅ From list of dictionaries
records = [{'A': 10, 'B': 20}, {'A': 30, 'B': 40}]
df = pd.DataFrame(records)
print(df)

✅ From a NumPy array
import numpy as np
arr = np.arange(6).reshape(3, 2)
df = pd.DataFrame(arr, columns=['A', 'B'])
print(df)

🔹 2. Accessing Structure Info
Explore structure
print(df.shape)      # (rows, columns)
print(df.columns)    # Index(['A', 'B'], dtype='object')
print(df.index)      # RangeIndex(start=0, stop=3, step=1)
print(df.dtypes)     # Column data types

Quick info summary
df.info()            # Non-null counts, dtypes, memory
print(df.describe()) # Stats summary for numeric cols

🔹 3. Viewing Data
print(df.head())      # First 5 rows
print(df.head(2))     # First 2 rows
print(df.tail())      # Last 5 rows

🔹 4. Column & Row Access
Access single or multiple columns
print(df['A'])        # Single column (Series)
print(df[['A', 'B']]) # Multiple columns (DataFrame)

Add or modify column
df['C'] = df['A'] + df['B']
print(df)

Row access (loc / iloc)
print(df.loc['x'])     # by label
print(df.iloc[0])      # by position

🔹 5. Basic Operations
Element-wise math
print(df * 2)
print(df + 5)

Column statistics
print(df['A'].mean())
print(df['B'].sum())

DataFrame-level
print(df.mean())    # Mean per column
print(df.sum())     # Sum per column
print(df.describe())

🔹 6. Rename, Drop, and Reindex
# Rename columns
df = df.rename(columns={'A': 'Alpha', 'B': 'Beta'})
print(df)

# Drop columns/rows
df = df.drop('Beta', axis=1)
print(df)

# Reindex
df = df.reindex(['z', 'y', 'x'])
print(df)

🔹 7. Attributes Recap
Attribute	Description	Example
.shape	Rows × Columns	df.shape
.index	Row labels	df.index
.columns	Column labels	df.columns
.values	NumPy array view	df.values
.dtypes	Column data types	df.dtypes
.T	Transpose	df.T
.empty	True if no elements	df.empty
.ndim	Number of dimensions	df.ndim
🔹 8. Summary Methods
Function	Description	Example
df.head(n)	First n rows	df.head(3)
df.tail(n)	Last n rows	df.tail(2)
df.info()	Column data overview	df.info()
df.describe()	Statistical summary	df.describe()
df.sample(n)	Random sample of rows	df.sample(2)
df.memory_usage()	Memory per column	df.memory_usage()
🧩 Summary — DataFrame Parameters & Exploration Tools
Parameter	Purpose	Example
data	Input data (dict, list, array, etc.)	{'A':[1,2]}
index	Custom row labels	index=['r1','r2']
columns	Custom column names	columns=['X','Y']
dtype	Force column data type	dtype=float
copy	Copy data or not	copy=True

✅ Tip:
Always start with:

df.info()
df.shape
df.columns
df.describe()


These four lines give you a complete snapshot of your dataset in seconds.

🧩 PART 2 — CORE DATA STRUCTURES - DataFrame

3️⃣ DataFrame — Two-Dimensional Powerhouse

🧠 Concept

A DataFrame is a 2D labeled data structure — like a spreadsheet or SQL table.
Each column is a Series, and all columns share the same row index.

📊 Think:

Rows = observations, Columns = features

### 🔹 1. Creating DataFrames
###### ✅ From a dictionary of lists

In [3]:
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data)
print(df)

   A  B
0  1  4
1  2  5
2  3  6

##### ✅ Using parameters of pd.DataFrame()

In [7]:
pd.DataFrame(
    data=None,
    index=None,
    columns=None,
    dtype=None,
    copy=False
)

# Example:
data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(data, index=['x', 'y', 'z'], dtype=float, copy=True)
print(df)

     A    B
x  1.0  4.0
y  2.0  5.0
z  3.0  6.0

In [9]:
#### ✅ From list of dictionaries
records = [{'A': 10, 'B': 20}, {'A': 30, 'B': 40}]
df = pd.DataFrame(records)
print(df)

    A   B
0  10  20
1  30  40

In [10]:
#### ✅ From a NumPy array
import numpy as np
import pandas as pd
arr = np.arange(12).reshape(3,4)
df = pd.DataFrame(arr,columns=['A','B','C','D'],index=['x','y','z'])
print(df)

   A  B   C   D
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

In [11]:
### Explore structure

print(df.shape)      # (rows, columns)
print(df.columns)    # Index(['A', 'B'], dtype='object')
print(df.index)      # RangeIndex(start=0, stop=3, step=1)
print(df.dtypes)     # Column data types

(3, 4)
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['x', 'y', 'z'], dtype='object')
A    int64
B    int64
C    int64
D    int64
dtype: object

In [12]:
# Quick info summary

df.info()            # Non-null counts, dtypes, memory
print(df.describe()) # Stats summary for numeric cols

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
 3   D       3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes
         A    B     C     D
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [17]:
# Viewing Data
print(df.head())      # First 5 rows
print()
print(df.head(2))     # First 2 rows
print()
print(df.tail())      # Last 5 rows
print()
print(df.tail(1))

   A  B   C   D
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

   A  B  C  D
x  0  1  2  3
y  4  5  6  7

   A  B   C   D
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

   A  B   C   D
z  8  9  10  11

In [19]:
# 🔹 Column & Row Access
# Access single or multiple columns
print(df['A'])       # Single column (Series)
print(df[['A', 'B']]) # Multiple columns (DataFrame)

x    0
y    4
z    8
Name: A, dtype: int64
   A  B
x  0  1
y  4  5
z  8  9

In [20]:
# Add or modify column
df['C'] = df['A'] + df['B']
print(df)

   A  B   C   D
x  0  1   1   3
y  4  5   9   7
z  8  9  17  11

In [21]:
# Row access (loc / iloc)

print(df.loc['x'])     # by label
print(df.iloc[0])      # by position

A    0
B    1
C    1
D    3
Name: x, dtype: int64
A    0
B    1
C    1
D    3
Name: x, dtype: int64

In [24]:
# 🔹 Basic Operations

# Element-wise math

print(df*2)
print()
print(df + 2)

    A   B   C   D
x   0   2   2   6
y   8  10  18  14
z  16  18  34  22

    A   B   C   D
x   2   3   3   5
y   6   7  11   9
z  10  11  19  13

In [27]:
# Column statistics

print(df['A'].mean())
print(df['B'].sum())
print(df['A'].median())
print(df['A'].count())

4.0
15
4.0
3

In [31]:
# DataFrame-level
print(df.head())
print()
print(df.mean())    # Mean per column
print()
print(df.sum())     # Sum per column
print()
print(df.describe())

   A  B   C   D
x  0  1   1   3
y  4  5   9   7
z  8  9  17  11

A    4.0
B    5.0
C    9.0
D    7.0
dtype: float64

A    12
B    15
C    27
D    21
dtype: int64

         A    B     C     D
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   9.0   7.0
std    4.0  4.0   8.0   4.0
min    0.0  1.0   1.0   3.0
25%    2.0  3.0   5.0   5.0
50%    4.0  5.0   9.0   7.0
75%    6.0  7.0  13.0   9.0
max    8.0  9.0  17.0  11.0

In [39]:
# 🔹  Rename, Drop, and Reindex

# Rename columns

print(df.head())
df = df.rename(columns={'A': 'Alpha', 'C': 'Cat'})
print(df)

# Drop columns/rows
df = df.drop('Cat', axis=1)
print(df)

# Reindex
df = df.reindex(['z', 'y', 'x'])
print(df)

   Alpha   C   D
z      8  17  11
y      4   9   7
x      0   1   3
   Alpha  Cat   D
z      8   17  11
y      4    9   7
x      0    1   3
   Alpha   D
z      8  11
y      4   7
x      0   3
   Alpha   D
z      8  11
y      4   7
x      0   3

In [42]:

print(df.T)

        z  y  x
Alpha   8  4  0
D      11  7  3

In [48]:
#  7. Attributes Recap

| Attribute  | Description          | Example      |
| ---------- | -------------------- | ------------ |
| `.shape`   | Rows × Columns       | `df.shape`   |
| `.index`   | Row labels           | `df.index`   |
| `.columns` | Column labels        | `df.columns` |
| `.values`  | NumPy array view     | `df.values`  |
| `.dtypes`  | Column data types    | `df.dtypes`  |
| `.T`       | Transpose            | `df.T`       |
| `.empty`   | True if no elements  | `df.empty`   |
| `.ndim`    | Number of dimensions | `df.ndim`    |

# 🧭 PART 3 — DATA INPUT & OUTPUT

Definition:

Reading and writing data is how you load external datasets into Pandas and export processed data back to files.

When:

Whenever you import/export datasets — from CSVs, Excel, SQL databases, JSON files, or APIs.

Where:

Used in data collection, ETL (Extract-Transform-Load), and data pipelines.

Why:

Because real-world data always lives outside your Python environment — in files or databases.

In [55]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [77]:
import pandas as pd

# -------------------------------------------
# 🔹 Step 1: Create small sample data
# -------------------------------------------
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 28],
    'Salary': [50000, 60000, 55000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# -------------------------------------------
# 🔹 Step 2: Save to multiple formats
# -------------------------------------------
df.to_csv('data.csv', index=False)          # Save as CSV
df.to_excel('output.xlsx', index=False)     # Save as Excel
df.to_json('data.json', orient='records')   # Save as JSON

# -------------------------------------------
# 🔹 Step 3: Read from those files
# -------------------------------------------
df_csv = pd.read_csv('data.csv')            # Read CSV
df_excel = pd.read_excel('output.xlsx')     # Read Excel
df_json = pd.read_json('data.json')         # Read JSON

# -------------------------------------------
# 🔹 Step 4: Display loaded data
# -------------------------------------------
print("\nCSV Loaded:")
print(df_csv)

print("\nExcel Loaded:")
print(df_excel)

print("\nJSON Loaded:")
print(df_json)

Original DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   28   55000

CSV Loaded:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   28   55000

Excel Loaded:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   28   55000

JSON Loaded:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   28   55000

Advanced:

Use chunksize= for large files.

pd.read_sql(query, engine) for database integration.
    
✅ Master Tip: Learn I/O formats early — every analysis starts with importing clean data.

🧹 PART 4 — DATA CLEANING & PREPROCESSING

5️⃣ Handling Missing Data

Definition: Process of identifying and fixing NaN values.

When: Datasets often have incomplete records.

Where: Before analysis or modeling.

Why: Missing values can distort statistics or ML results.

In [78]:

print(df.isna().sum())
df['Age'].fillna(df['Age'].mean(), inplace=True)
df.dropna(subset=['Salary'])

Name      0
Age       0
Salary    0
dtype: int64

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   28   55000

6️⃣ Data Transformation

Definition: Modifying data values or types for consistency or new features.
    
When: Before analysis, feature engineering, or normalization.
    
Where: In data pipelines, after loading data.
    
Why: To make raw data analysis-ready.

In [80]:
df['Salary'] = df['Salary'].apply(lambda x: x * 1.05)
df.rename(columns={'Name':'EmpName'}, inplace=True)
df['Age'] = df['Age'].astype(int)
df

   EmpName  Age   Salary
0    Alice   25  55125.0
1      Bob   30  66150.0
2  Charlie   28  60637.5

### 7️⃣ Removing Duplicates & Filtering

Definition: Eliminating redundant rows and selecting subsets of data.

When: When data contains duplicate or irrelevant records.

Where: After data collection.

Why: To ensure integrity and relevance.

In [85]:
df.drop_duplicates(subset='EmpName', keep='first', inplace=True)
df = df[df['Age'] > 25]
df

   EmpName  Age   Salary
1      Bob   30  66150.0
2  Charlie   28  60637.5

🧩 PART 5 — INDEXING, SELECTION & SUBSETTING

8️⃣ Selecting Data

Definition: Extracting specific rows/columns.
    
When: During analysis, exploration, and preprocessing.
    
Why: To focus on relevant data slices.

In [87]:
df.loc[df['Age'] > 25, ['EmpName','Age']]  # label-based
df.iloc[0:3, 1:3]                       # position-based

   Age   Salary
1   30  66150.0
2   28  60637.5

9️⃣ Setting & Resetting Index

Definition: Defining a column (or columns) as row labels.
    
When: When you need fast lookup or multi-level indexing.
    
Why: Makes slicing and merging efficient.

In [91]:
df.set_index('EmpName', inplace=True)
df.reset_index(inplace=True)
df

   EmpName  Age   Salary
0      Bob   30  66150.0
1  Charlie   28  60637.5

📊 PART 6 — DATA AGGREGATION & GROUPING

🔟 GroupBy Operations

Definition: Splitting data into groups and computing aggregate stats.
    
When: For summaries or segment-based analysis.
    
Why: To find insights per group (e.g., avg salary by department).

In [97]:
import pandas as pd

# -------------------------------------------
# 🔹 Step 1: Create sample employee dataset
# -------------------------------------------
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona'],
    'Gender': ['F', 'M', 'M', 'F', 'M', 'F'],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Finance', 'Finance'],
    'Salary': [50000, 60000, 55000, 52000, 70000, 68000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# -------------------------------------------
# 🔹 Step 2: Basic GroupBy — Mean Salary by Department
# -------------------------------------------
dept_mean = df.groupby('Department')['Salary'].mean()
print("\nMean Salary by Department:")
print(dept_mean)

# -------------------------------------------
# 🔹 Step 3: Advanced GroupBy — Multiple Columns & Aggregations
# -------------------------------------------
dept_gender_stats = df.groupby(['Department', 'Gender']).agg({
    'Salary': ['mean', 'max']
})
print("\nSalary Stats by Department & Gender:")
print(dept_gender_stats)

# -------------------------------------------
# 🔹 Step 4: Final DataFrame
# -------------------------------------------
print("\nFinal DataFrame:")
print(df)

Original DataFrame:
      Name Gender Department  Salary
0    Alice      F         HR   50000
1      Bob      M         IT   60000
2  Charlie      M         IT   55000
3    Diana      F         HR   52000
4    Ethan      M    Finance   70000
5    Fiona      F    Finance   68000

Mean Salary by Department:
Department
Finance    69000.0
HR         51000.0
IT         57500.0
Name: Salary, dtype: float64

Salary Stats by Department & Gender:
                    Salary
                      mean    max
Department Gender
Finance    F       68000.0  68000
           M       70000.0  70000
HR         F       51000.0  52000
IT         M       57500.0  60000

Final DataFrame:
      Name Gender Department  Salary
0    Alice      F         HR   50000
1      Bob      M         IT   60000
2  Charlie      M         IT   55000
3    Diana      F         HR   52000
4    Ethan      M    Finance   70000
5    Fiona      F    Finance   68000

| Concept                  | Function                                         | Use                                                |
| ------------------------ | ------------------------------------------------ | -------------------------------------------------- |
| **Single groupby**       | `df.groupby('Department')['Salary'].mean()`      | Calculate average salary per department            |
| **Multi-column groupby** | `df.groupby(['Department','Gender']).agg({...})` | Perform multiple aggregations by multiple columns  |
| **agg()**                | Combine different metrics (`mean`, `max`, etc.)  | For richer summaries like average + highest salary |

1️⃣1️⃣ Pivot Tables & Crosstab

Definition: Excel-like summary table by category.
    
When: When you need summarized metrics across two dimensions.
    
Why: Easy for reporting and dashboards.

In [101]:

import pandas as pd

# -------------------------------------------
# Step 1: Create sample sales data
# -------------------------------------------
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Year': [2023, 2023, 2023, 2023, 2024, 2024, 2024, 2024],
    'Sales': [12000, 10000, 8000, 9000, 15000, 11000, 9500, 10500]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# -------------------------------------------
# Step 2: Pivot Table — Summarize Sales by Region & Year
# -------------------------------------------
pivot = pd.pivot_table(df, values='Sales', index='Region', columns='Year', aggfunc='sum')
print("\nPivot Table (Total Sales by Region & Year):")
print(pivot)

# -------------------------------------------
# Step 3: Optional — Crosstab (alternative view)
# -------------------------------------------
crosstab = pd.crosstab(df['Region'], df['Year'], values=df['Sales'], aggfunc='sum')
print("\nCrosstab (Alternative Summary):")
print(crosstab)

Original DataFrame:
  Region  Year  Sales
0  North  2023  12000
1  South  2023  10000
2   East  2023   8000
3   West  2023   9000
4  North  2024  15000
5  South  2024  11000
6   East  2024   9500
7   West  2024  10500

Pivot Table (Total Sales by Region & Year):
Year     2023   2024
Region
East     8000   9500
North   12000  15000
South   10000  11000
West     9000  10500

Crosstab (Alternative Summary):
Year     2023   2024
Region
East     8000   9500
North   12000  15000
South   10000  11000
West     9000  10500

🔧 PART 7 — DATA MERGING & JOINING

Definition: Combining multiple DataFrames into one.
    
When: When data is spread across different files/tables.
    
Why: To bring related information together.

In [103]:
import pandas as pd

# -------------------------------------------
# Step 1: Create two DataFrames
# -------------------------------------------
df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 28, 30]
})

df2 = pd.DataFrame({
    'id': [3, 4, 5],
    'Department': ['HR', 'Finance', 'IT'],
    'Salary': [60000, 65000, 70000]
})

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# -------------------------------------------
# Step 2: Concatenate (stack vertically)
# -------------------------------------------
concat_df = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenated DataFrame (Vertical Stack):")
print(concat_df)

# -------------------------------------------
# Step 3: Merge (SQL-style join on 'id')
# -------------------------------------------
merged_df = pd.merge(df1, df2, on='id', how='inner')
print("\nMerged DataFrame (Inner Join on 'id'):")
print(merged_df)

# -------------------------------------------
# Step 4: Join (by index)
# -------------------------------------------
# Reindex df2 for demonstration
df2_indexed = df2.set_index('id')
df1_indexed = df1.set_index('id')

joined_df = df1_indexed.join(df2_indexed, lsuffix='_A', rsuffix='_B')
print("\nJoined DataFrame (by index):")
print(joined_df)

DataFrame 1:
   id     Name  Age
0   1    Alice   25
1   2      Bob   28
2   3  Charlie   30

DataFrame 2:
   id Department  Salary
0   3         HR   60000
1   4    Finance   65000
2   5         IT   70000

Concatenated DataFrame (Vertical Stack):
   id     Name   Age Department   Salary
0   1    Alice  25.0        NaN      NaN
1   2      Bob  28.0        NaN      NaN
2   3  Charlie  30.0        NaN      NaN
3   3      NaN   NaN         HR  60000.0
4   4      NaN   NaN    Finance  65000.0
5   5      NaN   NaN         IT  70000.0

Merged DataFrame (Inner Join on 'id'):
   id     Name  Age Department  Salary
0   3  Charlie   30         HR   60000

Joined DataFrame (by index):
       Name  Age Department   Salary
id
1     Alice   25        NaN      NaN
2       Bob   28        NaN      NaN
3   Charlie   30         HR  60000.0

✅ Summary:

concat() → stacking

merge() → relational join

join() → by index

🧮 PART 8 — STATISTICS & NUMERICAL OPS
1️⃣3️⃣ Descriptive Statistics

Definition: Statistical summaries for numeric data.

When: During Exploratory Data Analysis (EDA).

Why: To understand distributions, spread, and correlations.

In [117]:
print(df.describe())
print()
print("mean of year col",df['Year'].mean())
print(df.corr(numeric_only=True))

              Year         Sales
count     8.000000      8.000000
mean   2023.500000  10625.000000
std       0.534522   2150.581317
min    2023.000000   8000.000000
25%    2023.000000   9375.000000
50%    2023.500000  10250.000000
75%    2024.000000  11250.000000
max    2024.000000  15000.000000

mean of year col 2023.5
           Year     Sales
Year   1.000000  0.434959
Sales  0.434959  1.000000

1️⃣4️⃣ Window Functions

Definition: Rolling, expanding, or exponential computations over time windows.
    
When: In time-series or trend-based analysis.
    
Why: For moving averages, cumulative sums, etc.

In [119]:
df['Rolling_Mean'] = df['Sales'].rolling(window=3).mean()
df

  Region  Year  Sales  Rolling_Mean
0  North  2023  12000           NaN
1  South  2023  10000           NaN
2   East  2023   8000  10000.000000
3   West  2023   9000   9000.000000
4  North  2024  15000  10666.666667
5  South  2024  11000  11666.666667
6   East  2024   9500  11833.333333
7   West  2024  10500  10333.333333

🧩 Explanation

The first two rows are NaN because there aren’t 3 values yet to compute a mean.

From the 3rd row onward, each value is the average of the last 3 sales:

116.67 = mean(100,120,130)

133.33 = mean(120,130,150), etc.

| Function             | Description               |
| -------------------- | ------------------------- |
| `.rolling(n).sum()`  | Moving sum                |
| `.rolling(n).std()`  | Moving standard deviation |
| `.rolling(n).min()`  | Moving minimum            |
| `.rolling(n).max()`  | Moving maximum            |
| `.rolling(n).corr()` | Rolling correlation       |

🧠 PART 9 — TIME SERIES ANALYSIS

Definition: 
Time Series Analysis is working with date- or time-indexed data — analyzing trends, periodicity, and seasonality.
    
📅 When

Use it when your dataset involves temporal patterns, such as:

Stock market prices 📈

Monthly sales 📊

Daily temperatures 🌡️

IoT or sensor readings ⏱️.
    
💡 Why

Enables resampling (aggregate by day, month, year)

Allows shifting (lag/lead for trend comparison)

Simplifies time-based filtering & rolling analysis

In [121]:
import pandas as pd

# Sample daily sales data
data = {
    'Date': [
        '2024-01-01', '2024-01-02', '2024-01-03',
        '2024-02-01', '2024-02-02', '2024-02-03',
        '2024-03-01', '2024-03-02'
    ],
    'Sales': [200, 220, 210, 250, 270, 260, 300, 320]
}

df = pd.DataFrame(data)
print("Original Data:")
print(df)

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set Date as index for time-based operations
df.set_index('Date', inplace=True)

# Resample monthly — aggregate total sales by month
monthly_sales = df.resample('M').sum()

print("\nMonthly Sales (Resampled):")
print(monthly_sales)

Original Data:
         Date  Sales
0  2024-01-01    200
1  2024-01-02    220
2  2024-01-03    210
3  2024-02-01    250
4  2024-02-02    270
5  2024-02-03    260
6  2024-03-01    300
7  2024-03-02    320

Monthly Sales (Resampled):
            Sales
Date
2024-01-31    630
2024-02-29    780
2024-03-31    620

C:\Users\Vineeth Reddy\AppData\Local\Temp\ipykernel_11548\570219174.py:24: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales = df.resample('M').sum()

| Method                             | Purpose                                        |
| ---------------------------------- | ---------------------------------------------- |
| `df.shift(1)`                      | Shift values down by 1 day/month (lag feature) |
| `df.resample('W').mean()`          | Weekly average                                 |
| `df['Sales'].rolling('7D').mean()` | 7-day rolling average                          |
| `df.loc['2024-02']`                | Filter all February data                       |

In [122]:
import pandas as pd

# ------------------------------
# 📅 Create Sample Time Series Data
# ------------------------------
data = {
    'Date': pd.date_range(start='2024-01-01', periods=10, freq='D'),
    'Sales': [200, 210, 220, 250, 260, 270, 300, 310, 320, 330]
}

df = pd.DataFrame(data)
df.set_index('Date', inplace=True)
print("Original Data:\n", df, "\n")

# ------------------------------
# 1️⃣ Shift: Lag previous day's sales
# ------------------------------
df['Prev_Day_Sales'] = df['Sales'].shift(1)
print("After Shift (Lag Feature):\n", df, "\n")

# ------------------------------
# 2️⃣ Resample Weekly: Compute weekly mean
# ------------------------------
weekly_avg = df.resample('W').mean()
print("Weekly Average Sales:\n", weekly_avg, "\n")

# ------------------------------
# 3️⃣ Rolling Window: 7-day rolling average
# ------------------------------
df['7D_Rolling_Avg'] = df['Sales'].rolling('7D').mean()
print("7-Day Rolling Average:\n", df, "\n")

# ------------------------------
# 4️⃣ Filter Data: February only
# ------------------------------
feb_data = df.loc['2024-01-05':'2024-01-10']
print("Filtered (Custom Range Example ~ Feb-like slice):\n", feb_data, "\n")

Original Data:
             Sales
Date
2024-01-01    200
2024-01-02    210
2024-01-03    220
2024-01-04    250
2024-01-05    260
2024-01-06    270
2024-01-07    300
2024-01-08    310
2024-01-09    320
2024-01-10    330

After Shift (Lag Feature):
             Sales  Prev_Day_Sales
Date
2024-01-01    200             NaN
2024-01-02    210           200.0
2024-01-03    220           210.0
2024-01-04    250           220.0
2024-01-05    260           250.0
2024-01-06    270           260.0
2024-01-07    300           270.0
2024-01-08    310           300.0
2024-01-09    320           310.0
2024-01-10    330           320.0

Weekly Average Sales:
                  Sales  Prev_Day_Sales
Date
2024-01-07  244.285714           235.0
2024-01-14  320.000000           310.0

7-Day Rolling Average:
             Sales  Prev_Day_Sales  7D_Rolling_Avg
Date
2024-01-01    200             NaN      200.000000
2024-01-02    210           200.0      205.000000
2024-01-03    220           210.0      210.000000
2024-01-04    250           220.0      220.000000
2024-01-05    260           250.0      228.000000
2024-01-06    270           260.0      235.000000
2024-01-07    300           270.0      244.285714
2024-01-08    310           300.0      260.000000
2024-01-09    320           310.0      275.714286
2024-01-10    330           320.0      291.428571

Filtered (Custom Range Example ~ Feb-like slice):
             Sales  Prev_Day_Sales  7D_Rolling_Avg
Date
2024-01-05    260           250.0      228.000000
2024-01-06    270           260.0      235.000000
2024-01-07    300           270.0      244.285714
2024-01-08    310           300.0      260.000000
2024-01-09    320           310.0      275.714286
2024-01-10    330           320.0      291.428571

🧰 PART 10 — ADVANCED OPERATIONS (Pandas)

🔹 Definition:

Advanced Pandas operations let you handle complex data types (like categories, text, and hierarchies) and perform custom transformations efficiently.

These are powerful for real-world analytics, data cleaning, and feature engineering.

1️⃣ Categorical Data

Definition: Converts text columns with repeated values into categories for memory & performance efficiency.

When: Large datasets with repeated strings (e.g., “Department”, “Gender”).

Why: Saves memory and speeds up comparisons.

In [127]:
# Use case: Memory optimization, label encoding before ML.

import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'HR', 'IT']
})
df['Department'] = df['Department'].astype('category')
print(df.dtypes)
print(df.head())

Name            object
Department    category
dtype: object
      Name Department
0    Alice         HR
1      Bob         IT
2  Charlie         HR
3    David         IT

2️⃣ MultiIndex (Hierarchical Index)

Definition: Multi-level index for rows or columns → 2D+ structured data.
    
When: You have grouped or nested data.
    
Why: Easier summarization of complex tables (like Region → City → Sales).

In [134]:
arrays = [
    ['East', 'East', 'West', 'West'],
    ['CityA', 'CityB', 'CityC', 'CityD']
]
index = pd.MultiIndex.from_arrays(arrays, names=('Region', 'City'))
df = pd.DataFrame({'Sales': [100, 150, 200, 250]}, index=index)
print(df)

              Sales
Region City
East   CityA    100
       CityB    150
West   CityC    200
       CityD    250

In [137]:
# # ✅ Operations:

df.unstack()     # move one level to columns

        Sales
City    CityA  CityB  CityC  CityD
Region
East    100.0  150.0    NaN    NaN
West      NaN    NaN  200.0  250.0

In [136]:

df.stack()       # reverse it back

Region  City
East    CityA  Sales    100
        CityB  Sales    150
West    CityC  Sales    200
        CityD  Sales    250
dtype: int64

3️⃣ String Operations

Definition: Vectorized string methods for cleaning & transforming text.
    
When: Cleaning raw text (names, emails, etc.)
    
Why: Efficient alternative to Python string loops.

In [139]:
df = pd.DataFrame({'Email': ['alice@gmail.com', 'bob@yahoo.com', 'carol@gmail.com']})
df['Domain'] = df['Email'].str.split('@').str[1]
df['IsGmail'] = df['Email'].str.contains('gmail')
print(df)

             Email     Domain  IsGmail
0  alice@gmail.com  gmail.com     True
1    bob@yahoo.com  yahoo.com    False
2  carol@gmail.com  gmail.com     True

✅ Common string ops:
| Operation        | Description    |
| ---------------- | -------------- |
| `str.upper()`    | Uppercase      |
| `str.lower()`    | Lowercase      |
| `str.contains()` | Filter text    |
| `str.replace()`  | Clean patterns |
| `str.split()`    | Extract parts  |

4️⃣ Apply Custom Functions

Definition: Apply your own logic to transform columns or entire DataFrames.
    
When: You need transformations not covered by built-ins.
    
Why: Flexibility for custom preprocessing.

In [148]:
import pandas as pd

df = pd.DataFrame({'Score': [100, 27, 65, 75, 99]})

def normalize(series):
    return (series - series.min()) / (series.max() - series.min())

df['Normalized'] = normalize(df['Score'])
print(df)

   Score  Normalized
0    100    1.000000
1     27    0.000000
2     65    0.520548
3     75    0.657534
4     99    0.986301

| Function      | Scope                    | Example                |
| ------------- | ------------------------ | ---------------------- |
| `.apply()`    | Column-wise              | df['x'].apply(func)    |
| `.applymap()` | Element-wise             | df.applymap(str.upper) |
| `.map()`      | Series element transform | df['col'].map(func)    |

In [154]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['x', 'y', 'z']
})

# 1️⃣ apply() → column-wise
df['A_doubled'] = df['A'].apply(lambda x: x * 2)
print(df.head())
print()
# 2️⃣ applymap() → element-wise (for entire DataFrame)
df_str = df[['B']].applymap(str.upper)

print("\napplymap example:\n", df_str)
print()
# 3️⃣ map() → element transform (Series only)
df['B_mapped'] = df['B'].map({'x': 'X-ray', 'y': 'Yellow', 'z': 'Zebra'})

print(df)

   A  B  A_doubled
0  1  x          2
1  2  y          4
2  3  z          6


applymap example:
    B
0  X
1  Y
2  Z

   A  B  A_doubled B_mapped
0  1  x          2    X-ray
1  2  y          4   Yellow
2  3  z          6    Zebra

C:\Users\Vineeth Reddy\AppData\Local\Temp\ipykernel_11548\2917357677.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_str = df[['B']].applymap(str.upper)