# Pandas Complete Implementation for AI/ML

Run the cells from top to bottom.

## 1. Import Pandas

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

## 2. Series

In [4]:
marks = pd.Series([80, 90, 75, 88], name="Marks")
print(marks)

subject_marks = pd.Series(
    [80, 90, 75],
    index=["Maths", "Science", "English"],
    name="Marks"
)
print("\nCustom index:\n", subject_marks)

0    80
1    90
2    75
3    88
Name: Marks, dtype: int64

Custom index:
 Maths      80
Science    90
English    75
Name: Marks, dtype: int64

## 3. DataFrame

In [7]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 106],
    "Name": [" Vineeth ", "Harshitha", "Priya", "Arjun", "Sneha", "Kiran", "Kiran"],
    "Department": ["AI", "HR", "AI", "Finance", "HR", "AI", "AI"],
    "Age": [25, 28, 24, 30, np.nan, 27, 27],
    "Salary": [70000, 50000, 65000, 60000, 52000, np.nan, np.nan],
    "Experience": [4, 5, 3, 6, 2, 4, 4],
    "City": ["Hyderabad", "Bangalore", "Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Hyderabad"]
}

df = pd.DataFrame(data)
df

   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

## 4. Save Sample Data and Read CSV

In [9]:
df.to_csv("employees_sample.csv", index=False)
csv_df = pd.read_csv("employees_sample.csv")
csv_df.head()

   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore

## 5. Read / Write JSON

In [11]:
df.to_json("employees_sample.json", orient="records", indent=2)
json_df = pd.read_json("employees_sample.json")
json_df.head()

   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore

## 6. Read / Write Excel

In [13]:
try:
    df.to_excel("employees_sample.xlsx", index=False)
    excel_df = pd.read_excel("employees_sample.xlsx")
    print(excel_df.head())
except ImportError as e:
    print("Excel support requires openpyxl. Install it with: pip install openpyxl")

   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore

## 7. Inspect Data

In [15]:
print("HEAD")
print(df.head(2))

print("\nTAIL")
print(df.tail(2))

print("\nSHAPE:", df.shape)
print("\nCOLUMNS:", df.columns.tolist())
print("\nDTYPES:\n", df.dtypes)

print("\nINFO")
df.info()

print("\nDESCRIBE")
print(df.describe())

print("\nDESCRIBE ALL")
print(df.describe(include="all"))

HEAD
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore

TAIL
   Employee_ID   Name Department   Age  Salary  Experience       City
5          106  Kiran         AI  27.0     NaN           4  Hyderabad
6          106  Kiran         AI  27.0     NaN           4  Hyderabad

SHAPE: (7, 7)

COLUMNS: ['Employee_ID', 'Name', 'Department', 'Age', 'Salary', 'Experience', 'City']

DTYPES:
 Employee_ID      int64
Name            object
Department      object
Age            float64
Salary         float64
Experience       int64
City            object
dtype: object

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  7 non-null      int64
 1   Name         7 non-null      object
 2   Department   7 non-null      object
 3   Age          6 non-null      float64
 4   Salary       5 non-null      float64
 5   Experience   7 non-null      int64
 6   City         7 non-null      object
dtypes: float64(2), int64(2), object(3)
memory usage: 520.0+ bytes

DESCRIBE
       Employee_ID        Age        Salary  Experience
count     7.000000   6.000000      5.000000    7.000000
mean    103.857143  26.833333  59400.000000    4.000000
std       1.951800   2.136976   8473.488066    1.290994
min     101.000000  24.000000  50000.000000    2.000000
25%     102.500000  25.500000  52000.000000    3.500000
50%     104.000000  27.000000  60000.000000    4.000000
75%     105.500000  27.750000  65000.000000    4.500000
max     106.000000  30.000000  70000.000000    6.000000

DESCRIBE ALL
        Employee_ID   Name Department        Age        Salary  Experience  \
count      7.000000      7          7   6.000000      5.000000    7.000000
unique          NaN      6          3        NaN           NaN         NaN
top             NaN  Kiran         AI        NaN           NaN         NaN
freq            NaN      2          4        NaN           NaN         NaN
mean     103.857143    NaN        NaN  26.833333  59400.000000    4.000000
std        1.951800    NaN        NaN   2.136976   8473.488066    1.290994
min      101.000000    NaN        NaN  24.000000  50000.000000    2.000000
25%      102.500000    NaN        NaN  25.500000  52000.000000    3.500000
50%      104.000000    NaN        NaN  27.000000  60000.000000    4.000000
75%      105.500000    NaN        NaN  27.750000  65000.000000    4.500000
max      106.000000    NaN        NaN  30.000000  70000.000000    6.000000

             City
count           7
unique          3
top     Hyderabad
freq            4
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

## 8. Selecting Columns

In [17]:
print("Single column (Series):")
print(df["Name"])

print("\nMultiple columns (DataFrame):")
print(df[["Name", "Department", "Salary"]])

Single column (Series):
0     Vineeth
1    Harshitha
2        Priya
3        Arjun
4        Sneha
5        Kiran
6        Kiran
Name: Name, dtype: object

Multiple columns (DataFrame):
        Name Department   Salary
0   Vineeth          AI  70000.0
1  Harshitha         HR  50000.0
2      Priya         AI  65000.0
3      Arjun    Finance  60000.0
4      Sneha         HR  52000.0
5      Kiran         AI      NaN
6      Kiran         AI      NaN

## 9. loc and iloc

In [23]:
print("loc row 0:")
print(df.head())
print(df.loc[1])

print("\nloc rows 0:2, selected columns:")
print(df.loc[0:2, ["Name", "Salary"]])

print("\niloc first 3 rows, first 3 columns:")
print(df.iloc[0:3, 0:3])

loc row 0:
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore
Employee_ID          102
Name           Harshitha
Department            HR
Age                 28.0
Salary           50000.0
Experience             5
City           Bangalore
Name: 1, dtype: object

loc rows 0:2, selected columns:
        Name   Salary
0   Vineeth   70000.0
1  Harshitha  50000.0
2      Priya  65000.0

iloc first 3 rows, first 3 columns:
   Employee_ID       Name Department
0          101   Vineeth          AI
1          102  Harshitha         HR
2          103      Priya         AI

## 10. Filtering

In [24]:
print("Salary > 55000")
print(df[df["Salary"] > 55000])

print("\nAI employees")
print(df[df["Department"] == "AI"])

print("\nAI AND Experience >= 4")
print(df[(df["Department"] == "AI") & (df["Experience"] >= 4)])

print("\nHyderabad OR Chennai")
print(df[(df["City"] == "Hyderabad") | (df["City"] == "Chennai")])

print("\nisin")
print(df[df["Department"].isin(["AI", "Finance"])])

print("\nbetween")
print(df[df["Salary"].between(50000, 65000)])

Salary > 55000
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai

AI employees
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

AI AND Experience >= 4
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

Hyderabad OR Chennai
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

isin
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

between
   Employee_ID       Name Department   Age   Salary  Experience       City
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore

## 11. Missing Values

In [25]:
print("Missing matrix:\n", df.isnull())
print("\nMissing count:\n", df.isnull().sum())
print("\nNon-missing count:\n", df.notnull().sum())

Missing matrix:
    Employee_ID   Name  Department    Age  Salary  Experience   City
0        False  False       False  False   False       False  False
1        False  False       False  False   False       False  False
2        False  False       False  False   False       False  False
3        False  False       False  False   False       False  False
4        False  False       False   True   False       False  False
5        False  False       False  False    True       False  False
6        False  False       False  False    True       False  False

Missing count:
 Employee_ID    0
Name           0
Department     0
Age            1
Salary         2
Experience     0
City           0
dtype: int64

Non-missing count:
 Employee_ID    7
Name           7
Department     7
Age            6
Salary         5
Experience     7
City           7
dtype: int64

## 12. Fill Missing Values

In [28]:
df_clean = df.copy()

df_clean["Age"] = df_clean["Age"].fillna(df_clean["Age"].median())

dept_salary_mean = df_clean.groupby("Department")["Salary"].transform("mean")
df_clean["Salary"] = df_clean["Salary"].fillna(dept_salary_mean)
df_clean["Salary"] = df_clean["Salary"].fillna(df_clean["Salary"].median())

print(df_clean)

   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore
5          106      Kiran         AI  27.0  67500.0           4  Hyderabad
6          106      Kiran         AI  27.0  67500.0           4  Hyderabad

## 13. dropna, ffill and bfill

In [30]:
print("dropna result:")
print(df.dropna())

print("\nForward fill:")
print(df.ffill())

print("\nBackward fill:")
print(df.bfill())

dropna result:
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai

Forward fill:
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  30.0  52000.0           2  Bangalore
5          106      Kiran         AI  27.0  52000.0           4  Hyderabad
6          106      Kiran         AI  27.0  52000.0           4  Hyderabad

Backward fill:
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore
5          106      Kiran         AI  27.0      NaN           4  Hyderabad
6          106      Kiran         AI  27.0      NaN           4  Hyderabad

## 14. Duplicate Handling

In [33]:
print("Duplicate mask:")
print(df.duplicated())

print("\nDuplicate count:", df.duplicated().sum())

df_no_dupes = df.drop_duplicates(subset=["Employee_ID"], keep="first")
print("\nAfter removing duplicate Employee_ID:")
print(df_no_dupes)

Duplicate mask:
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

Duplicate count: 1

After removing duplicate Employee_ID:
   Employee_ID       Name Department   Age   Salary  Experience       City
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR   NaN  52000.0           2  Bangalore
5          106      Kiran         AI  27.0      NaN           4  Hyderabad

## 15. String Cleaning

In [35]:
df_strings = df.copy()
df_strings["Name"] = df_strings["Name"].str.strip()

print("Uppercase names:")
print(df_strings["Name"].str.upper())

print("\nLowercase names:")
print(df_strings["Name"].str.lower())

print("\nName lengths:")
print(df_strings["Name"].str.len())

print("\nContains Hyderabad:")
print(df_strings[df_strings["City"].str.contains("hyderabad", case=False, na=False)])

Uppercase names:
0      VINEETH
1    HARSHITHA
2        PRIYA
3        ARJUN
4        SNEHA
5        KIRAN
6        KIRAN
Name: Name, dtype: object

Lowercase names:
0      vineeth
1    harshitha
2        priya
3        arjun
4        sneha
5        kiran
6        kiran
Name: Name, dtype: object

Name lengths:
0    7
1    9
2    5
3    5
4    5
5    5
6    5
Name: Name, dtype: int64

Contains Hyderabad:
   Employee_ID     Name Department   Age   Salary  Experience       City
0          101  Vineeth         AI  25.0  70000.0           4  Hyderabad
2          103    Priya         AI  24.0  65000.0           3  Hyderabad
5          106    Kiran         AI  27.0      NaN           4  Hyderabad
6          106    Kiran         AI  27.0      NaN           4  Hyderabad

## 16. Add New Columns

In [37]:
work = df_clean.drop_duplicates(subset=["Employee_ID"]).copy()

work["Country"] = "India"
work["Annual_Salary"] = work["Salary"] * 12
work["Bonus"] = work["Salary"] * 0.10
work["Experience_Level"] = np.where(work["Experience"] >= 5, "Senior", "Junior")

work

,Employee_ID,Name,Department,Age,Salary,Experience,City,Country,Annual_Salary,Bonus,Experience_Level
0,101,Vineeth,AI,25.0,70000.0,4,Hyderabad,India,840000.0,7000.0,Junior
1,102,Harshitha,HR,28.0,50000.0,5,Bangalore,India,600000.0,5000.0,Senior
2,103,Priya,AI,24.0,65000.0,3,Hyderabad,India,780000.0,6500.0,Junior
3,104,Arjun,Finance,30.0,60000.0,6,Chennai,India,720000.0,6000.0,Senior
4,105,Sneha,HR,27.0,52000.0,2,Bangalore,India,624000.0,5200.0,Junior
5,106,Kiran,AI,27.0,67500.0,4,Hyderabad,India,810000.0,6750.0,Junior

## 17. Multiple Conditions with np.select

In [41]:
conditions = [
    work["Experience"] < 3,
    work["Experience"].between(3, 5),
    work["Experience"] > 5
]
choices = ["Beginner", "Intermediate", "Senior"]

work["Level"] = np.select(conditions, choices, default="Unknown")
work[["Name", "Experience", "Level"]]

        Name  Experience         Level
0   Vineeth            4  Intermediate
1  Harshitha           5  Intermediate
2      Priya           3  Intermediate
3      Arjun           6        Senior
4      Sneha           2      Beginner
5      Kiran           4  Intermediate

## 18. Update Values with loc

In [42]:
updated = work.copy()
updated.loc[updated["Department"] == "AI", "Salary"] += 5000
updated[["Name", "Department", "Salary"]]

        Name Department   Salary
0   Vineeth          AI  75000.0
1  Harshitha         HR  50000.0
2      Priya         AI  70000.0
3      Arjun    Finance  60000.0
4      Sneha         HR  52000.0
5      Kiran         AI  72500.0

## 19. Rename and Drop

In [43]:
renamed = work.rename(columns={"Employee_ID": "ID", "Department": "Dept"})
print(renamed.head())

dropped = work.drop(columns=["Country"])
print("\nAfter dropping Country:\n", dropped.head())

    ID       Name     Dept   Age   Salary  Experience       City Country  \
0  101   Vineeth        AI  25.0  70000.0           4  Hyderabad   India
1  102  Harshitha       HR  28.0  50000.0           5  Bangalore   India
2  103      Priya       AI  24.0  65000.0           3  Hyderabad   India
3  104      Arjun  Finance  30.0  60000.0           6    Chennai   India
4  105      Sneha       HR  27.0  52000.0           2  Bangalore   India

   Annual_Salary   Bonus Experience_Level         Level
0       840000.0  7000.0           Junior  Intermediate
1       600000.0  5000.0           Senior  Intermediate
2       780000.0  6500.0           Junior  Intermediate
3       720000.0  6000.0           Senior        Senior
4       624000.0  5200.0           Junior      Beginner

After dropping Country:
    Employee_ID       Name Department   Age   Salary  Experience       City  \
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore

   Annual_Salary   Bonus Experience_Level         Level
0       840000.0  7000.0           Junior  Intermediate
1       600000.0  5000.0           Senior  Intermediate
2       780000.0  6500.0           Junior  Intermediate
3       720000.0  6000.0           Senior        Senior
4       624000.0  5200.0           Junior      Beginner

## 20. Sorting

In [45]:
print(work.sort_values("Salary"))
print("\nDescending:\n", work.sort_values("Salary", ascending=False))
print("\nMultiple columns:\n", work.sort_values(["Department", "Salary"], ascending=[True, False]))

   Employee_ID       Name Department   Age   Salary  Experience       City  \
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
4          105      Sneha         HR  27.0  52000.0           2  Bangalore
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
5          106      Kiran         AI  27.0  67500.0           4  Hyderabad
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad

  Country  Annual_Salary   Bonus Experience_Level         Level
1   India       600000.0  5000.0           Senior  Intermediate
4   India       624000.0  5200.0           Junior      Beginner
3   India       720000.0  6000.0           Senior        Senior
2   India       780000.0  6500.0           Junior  Intermediate
5   India       810000.0  6750.0           Junior  Intermediate
0   India       840000.0  7000.0           Junior  Intermediate

Descending:
    Employee_ID       Name Department   Age   Salary  Experience       City  \
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
5          106      Kiran         AI  27.0  67500.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore

  Country  Annual_Salary   Bonus Experience_Level         Level
0   India       840000.0  7000.0           Junior  Intermediate
5   India       810000.0  6750.0           Junior  Intermediate
2   India       780000.0  6500.0           Junior  Intermediate
3   India       720000.0  6000.0           Senior        Senior
4   India       624000.0  5200.0           Junior      Beginner
1   India       600000.0  5000.0           Senior  Intermediate

Multiple columns:
    Employee_ID       Name Department   Age   Salary  Experience       City  \
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
5          106      Kiran         AI  27.0  67500.0           4  Hyderabad
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore

  Country  Annual_Salary   Bonus Experience_Level         Level
0   India       840000.0  7000.0           Junior  Intermediate
5   India       810000.0  6750.0           Junior  Intermediate
2   India       780000.0  6500.0           Junior  Intermediate
3   India       720000.0  6000.0           Senior        Senior
4   India       624000.0  5200.0           Junior      Beginner
1   India       600000.0  5000.0           Senior  Intermediate

## 21. Aggregations

In [46]:
salary = work["Salary"]

print("sum:", salary.sum())
print("mean:", salary.mean())
print("median:", salary.median())
print("min:", salary.min())
print("max:", salary.max())
print("std:", salary.std())
print("var:", salary.var())
print("count:", salary.count())

print("\nMultiple aggregations:")
print(salary.agg(["min", "max", "mean", "sum"]))

sum: 364500.0
mean: 60750.0
median: 62500.0
min: 50000.0
max: 70000.0
std: 8268.917704270614
var: 68375000.0
count: 6

Multiple aggregations:
min      50000.0
max      70000.0
mean     60750.0
sum     364500.0
Name: Salary, dtype: float64

## 22. value_counts, unique and nunique

In [48]:
print(work["Department"].value_counts())
print("\nPercentages:\n", work["Department"].value_counts(normalize=True) * 100)
print("\nUnique values:", work["Department"].unique())
print("Unique count:", work["Department"].nunique())

Department
AI         3
HR         2
Finance    1
Name: count, dtype: int64

Percentages:
 Department
AI         50.000000
HR         33.333333
Finance    16.666667
Name: proportion, dtype: float64

Unique values: ['AI' 'HR' 'Finance']
Unique count: 3

## 23. GroupBy

In [49]:
print("Average salary by department:")
print(work.groupby("Department")["Salary"].mean())

print("\nMultiple aggregations:")
print(
    work.groupby("Department")["Salary"]
        .agg(["count", "mean", "min", "max"])
)

summary = (
    work.groupby("Department", as_index=False)
        .agg(
            Employee_Count=("Employee_ID", "count"),
            Average_Salary=("Salary", "mean"),
            Maximum_Salary=("Salary", "max"),
            Average_Experience=("Experience", "mean")
        )
)
summary

Average salary by department:
Department
AI         67500.0
Finance    60000.0
HR         51000.0
Name: Salary, dtype: float64

Multiple aggregations:
            count     mean      min      max
Department
AI              3  67500.0  65000.0  70000.0
Finance         1  60000.0  60000.0  60000.0
HR              2  51000.0  50000.0  52000.0

,Department,Employee_Count,Average_Salary,Maximum_Salary,Average_Experience
0,AI,3,67500.0,70000.0,3.666667
1,Finance,1,60000.0,60000.0,6.000000
2,HR,2,51000.0,52000.0,3.500000

## 24. GroupBy transform

In [50]:
tmp = work.copy()
tmp["Department_Avg_Salary"] = tmp.groupby("Department")["Salary"].transform("mean")
tmp[["Name", "Department", "Salary", "Department_Avg_Salary"]]

        Name Department   Salary  Department_Avg_Salary
0   Vineeth          AI  70000.0                67500.0
1  Harshitha         HR  50000.0                51000.0
2      Priya         AI  65000.0                67500.0
3      Arjun    Finance  60000.0                60000.0
4      Sneha         HR  52000.0                51000.0
5      Kiran         AI  67500.0                67500.0

## 25. apply, lambda and map

In [52]:
def salary_category(salary):
    if salary >= 65000:
        return "High"
    elif salary >= 55000:
        return "Medium"
    return "Low"

tmp = work.copy()
tmp["Salary_Category"] = tmp["Salary"].apply(salary_category)
tmp["Bonus_Vectorized"] = tmp["Salary"] * 0.10

department_codes = {"AI": 1, "HR": 2, "Finance": 3}
tmp["Department_Code"] = tmp["Department"].map(department_codes)

tmp[["Name", "Salary", "Salary_Category", "Department", "Department_Code"]]

        Name   Salary Salary_Category Department  Department_Code
0   Vineeth   70000.0            High         AI                1
1  Harshitha  50000.0             Low         HR                2
2      Priya  65000.0            High         AI                1
3      Arjun  60000.0          Medium    Finance                3
4      Sneha  52000.0             Low         HR                2
5      Kiran  67500.0            High         AI                1

## 26. Concatenation

In [58]:
df1 = pd.DataFrame({"Name": ["A", "B"], "Salary": [50000, 60000]})
df2 = pd.DataFrame({"Name": ["C", "D"], "Salary": [55000, 65000]})
print(df1.head())
print(df2.head())
combined = pd.concat([df1, df2], ignore_index=True)
combined

  Name  Salary
0    A   50000
1    B   60000
  Name  Salary
0    C   55000
1    D   65000

  Name  Salary
0    A   50000
1    B   60000
2    C   55000
3    D   65000

## 27. Merge / SQL-style Joins

In [60]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103],
    "Name": ["Vineeth", "Rahul", "Priya"]
})

departments = pd.DataFrame({
    "Employee_ID": [101, 102, 104],
    "Department": ["AI", "HR", "Finance"]
})

print("INNER")
print(pd.merge(employees, departments, on="Employee_ID", how="inner"))

print("\nLEFT")
print(pd.merge(employees, departments, on="Employee_ID", how="left"))

print("\nRIGHT")
print(pd.merge(employees, departments, on="Employee_ID", how="right"))

print("\nOUTER")
print(pd.merge(employees, departments, on="Employee_ID", how="outer"))

INNER
   Employee_ID     Name Department
0          101  Vineeth         AI
1          102    Rahul         HR

LEFT
   Employee_ID     Name Department
0          101  Vineeth         AI
1          102    Rahul         HR
2          103    Priya        NaN

RIGHT
   Employee_ID     Name Department
0          101  Vineeth         AI
1          102    Rahul         HR
2          104      NaN    Finance

OUTER
   Employee_ID     Name Department
0          101  Vineeth         AI
1          102    Rahul         HR
2          103    Priya        NaN
3          104      NaN    Finance

## 28. Date and Time Handling

In [62]:
sales = pd.DataFrame({
    "Date": ["2026-08-01", "2026-08-02", "2026-08-03", "2026-09-01"],
    "Sales": [10000, 15000, 12000, 18000]
})

sales["Date"] = pd.to_datetime(sales["Date"])
sales["Year"] = sales["Date"].dt.year
sales["Month"] = sales["Date"].dt.month
sales["Day"] = sales["Date"].dt.day
sales["Day_Name"] = sales["Date"].dt.day_name()

sales

        Date  Sales  Year  Month  Day  Day_Name
0 2026-08-01  10000  2026      8    1  Saturday
1 2026-08-02  15000  2026      8    2    Sunday
2 2026-08-03  12000  2026      8    3    Monday
3 2026-09-01  18000  2026      9    1   Tuesday

## 29. Pivot Table and Crosstab

In [66]:

pivot = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="mean",
    fill_value=0
)
print("Pivot table:\n", pivot)

print("\nCrosstab:\n", pd.crosstab(work["Department"], work["City"]))

Pivot table:
 City        Bangalore  Chennai  Hyderabad
Department
AI                0.0      0.0    67500.0
Finance           0.0  60000.0        0.0
HR            51000.0      0.0        0.0

Crosstab:
 City        Bangalore  Chennai  Hyderabad
Department
AI                  0        0          3
Finance             0        1          0
HR                  2        0          0

## 30. Set and Reset Index

In [67]:
indexed = work.set_index("Employee_ID")
print(indexed.head())

reset = indexed.reset_index()
print("\nReset:\n", reset.head())

                  Name Department   Age   Salary  Experience       City  \
Employee_ID
101           Vineeth          AI  25.0  70000.0           4  Hyderabad
102          Harshitha         HR  28.0  50000.0           5  Bangalore
103              Priya         AI  24.0  65000.0           3  Hyderabad
104              Arjun    Finance  30.0  60000.0           6    Chennai
105              Sneha         HR  27.0  52000.0           2  Bangalore

            Country  Annual_Salary   Bonus Experience_Level         Level
Employee_ID
101           India       840000.0  7000.0           Junior  Intermediate
102           India       600000.0  5000.0           Senior  Intermediate
103           India       780000.0  6500.0           Junior  Intermediate
104           India       720000.0  6000.0           Senior        Senior
105           India       624000.0  5200.0           Junior      Beginner

Reset:
    Employee_ID       Name Department   Age   Salary  Experience       City  \
0          101   Vineeth          AI  25.0  70000.0           4  Hyderabad
1          102  Harshitha         HR  28.0  50000.0           5  Bangalore
2          103      Priya         AI  24.0  65000.0           3  Hyderabad
3          104      Arjun    Finance  30.0  60000.0           6    Chennai
4          105      Sneha         HR  27.0  52000.0           2  Bangalore

  Country  Annual_Salary   Bonus Experience_Level         Level
0   India       840000.0  7000.0           Junior  Intermediate
1   India       600000.0  5000.0           Senior  Intermediate
2   India       780000.0  6500.0           Junior  Intermediate
3   India       720000.0  6000.0           Senior        Senior
4   India       624000.0  5200.0           Junior      Beginner

## 31. Correlation

In [68]:
numeric_cols = work.select_dtypes(include="number")
print(numeric_cols.corr())

               Employee_ID       Age    Salary  Experience  Annual_Salary  \
Employee_ID       1.000000  0.325169 -0.074339   -0.226779      -0.074339
Age               0.325169  1.000000 -0.500835    0.661783      -0.500835
Salary           -0.074339 -0.500835  1.000000    0.017103       1.000000
Experience       -0.226779  0.661783  0.017103    1.000000       0.017103
Annual_Salary    -0.074339 -0.500835  1.000000    0.017103       1.000000
Bonus            -0.074339 -0.500835  1.000000    0.017103       1.000000

                  Bonus
Employee_ID   -0.074339
Age           -0.500835
Salary         1.000000
Experience     0.017103
Annual_Salary  1.000000
Bonus          1.000000

## 32. Rolling Window Example

In [69]:
daily = pd.DataFrame({
    "Day": pd.date_range("2026-08-01", periods=7),
    "Sales": [100, 120, 90, 140, 160, 150, 180]
})

daily["3_Day_Moving_Average"] = daily["Sales"].rolling(3).mean()
daily

         Day  Sales  3_Day_Moving_Average
0 2026-08-01    100                   NaN
1 2026-08-02    120                   NaN
2 2026-08-03     90            103.333333
3 2026-08-04    140            116.666667
4 2026-08-05    160            130.000000
5 2026-08-06    150            150.000000
6 2026-08-07    180            163.333333

## 33. SQLite Integration

In [71]:
import sqlite3

connection = sqlite3.connect(":memory:")
work.to_sql("employees", connection, index=False, if_exists="replace")

sql_result = pd.read_sql(
    "SELECT Department, AVG(Salary) AS AvgSalary FROM employees GROUP BY Department",
    connection
)

print(sql_result)
connection.close()

  Department  AvgSalary
0         AI    67500.0
1    Finance    60000.0
2         HR    51000.0

## 34. Save Cleaned Outputs

In [72]:
work.to_csv("cleaned_employees.csv", index=False)
work.to_json("cleaned_employees.json", orient="records", indent=2)

print("Saved cleaned_employees.csv and cleaned_employees.json")

Saved cleaned_employees.csv and cleaned_employees.json

## Pandas Quick Revision

Covered:

- Series and DataFrame
- CSV / JSON / Excel I/O
- `head`, `tail`, `shape`, `columns`, `dtypes`, `info`, `describe`
- Column selection
- `loc` / `iloc`
- Filtering
- Missing values
- Duplicates
- String operations
- Adding/updating/renaming/dropping columns
- Sorting
- Aggregations
- `value_counts`, `unique`, `nunique`
- `groupby`, `agg`, `transform`
- `apply`, lambda, `map`
- `concat`
- `merge` joins
- Dates
- Pivot tables / crosstabs
- Index management
- Correlation
- Rolling calculations
- SQL integration
- Saving outputs